= Introduction

The Cascade Validation Plugin provides a small, focused extension to Grails constraints that makes it easy to validate associated objects (domain associations or command object) as part of normal validation.
Instead of manually calling validate() on every association, the plugin supplies a constraint (see usage) that marks an association to be validated automatically.

== Breaking changes.

Due to a change in Hibernate, there is a name clash with the `cascade` constraint keyword.
For this reason `cascade` was renamed to  `cascaded`.
Please update all your domain and command classes accordingly.
Search for `cascade: true` (or `cascade: false`) and replace with `cascaded: true` (or `false`). 

The constraint class was renamed from `CascadeConstraint` to `CascadedConstraint` and the registration class from `CascadeConstraintRegistration` to `CascadedConstraintRegistration` 

The previous format for the `field` name on collections was `field.0.childProperty`, but since 
Grails 7 does cascade validations on Domain objects, and the format for errors in this validation is `field[0].childProperty` a configuration property was added, to control if the legacy format should be used, or if the new format is used:

[source,yaml]
----
constraints:
    cascaded:
        legacy: true # default to false
----
