= Usage

ifndef::src[:src: ../../../]
ifndef::example[:example: {src}/cascade-validation-example]

== General usage

The constraint can be applied in two ways, either as `cascaded: true` or as a `Closure<Boolean>`:

[source,groovy]
----
class Person {
    Address address
    List<Phone> phones
    boolean shouldValidatePhones
    static constraints = { 
      // Will enable cascade for the Address property
      address cascaded: true 
      // Will enable cascade for all phone numbers if `shouldValidatePhones` is true
      phones cascaded: { property, target -> 
        target.shouldValidatePhones 
      }
    }
}
----


Another example can be found in `ValidateableParent` below.

== Domain example

[source,groovy,subs=attributes+]
----
include::{example}/grails-app/domain/cascade/Person.groovy[tag=domain]
----

[source,groovy,subs=attributes+]
----
include::{example}/grails-app/domain/cascade/PhoneNumber.groovy[tag=domain]
----

[source,groovy,subs=attributes+]
----
include::{example}/grails-app/domain/cascade/TelephoneType.groovy[tag=domain]
----

=== Explanation:

- When `Person.validate()` runs, the plugin will validate the list of `PhoneNumber` instances in the phoneNumber collection when `cascaded: true` is configured for that property.
When each `PhoneNumber` are validated, `cascaded` is also applied to `TelephoneType`

== Service usage

In a Data service, you can save, and validation is automatically applied

[source,groovy,subs=attributes+]
----
include::{example}/grails-app/services/cascade/PersonDataService.groovy[]
----

See the test case:

[source,groovy,subs=attributes+]
----
include::{example}/src/integration-test/groovy/cascade/PersonDataServiceSpec.groovy[]
----

== Databinding usage

When binding data to  `grails.validation.Validateable` objects (e.g., via controllers or REST endpoints), call `validate()` or rely on automatic validation in data-binding flows, the `CascadeConstraint` ensures marked associations are validated as part of the root object validation.

This can be illustrated with two examples:

=== A one-to-one relationship

[source,groovy,subs=attributes+]
----
include::{src}/src/test/groovy/grails/cascade/validation/support/ValidateableParent.groovy[tag=code]
----

[source,groovy,subs=attributes+]
----
include::{src}/src/test/groovy/grails/cascade/validation/support/ValidateableProperty.groovy[tag=code]
----

=== A one-to-many relationship

[source,groovy,subs=attributes+]
----
include::{src}/src/test/groovy/grails/cascade/validation/support/ValidateableParentWithChildList.groovy[tag=code]
----

[source,groovy,subs=attributes+]
----
include::{src}/src/test/groovy/grails/cascade/validation/support/ValidateableProperty.groovy[tag=code]
----

=== Note on unit-test

To unit-test your cascade associations, it is important to initialize the `CascadingConstraints` first.
To do so add

[source,groovy,subs=attributes+]
----
include::{example}/src/test/groovy/cascade/PersonCascadeSpec.groovy[tag=initialize]
----

to your `void setup() {}` block.

See `cascade-validation-example/src/test/groovy/cascade/PersonCascadeSpec.groovy` for more examples.

