[[usage]]
== Usage

=== General usage

The constraint can be applied in two ways, either as `cascaded: true` or as a `Closure<Boolean>`:

[source,groovy]
----
class Person {
    Address address
    List<Phone> phones
    boolean shouldValidatePhones

    static constraints = {
        // Will enable cascade for the Address property
        address cascaded: true
        // Will enable cascade for all phone numbers if `shouldValidatePhones` is true
        phones cascaded: { property, target ->
            target.shouldValidatePhones
        }
    }
}
----

=== Domain example

[source,groovy]
----
include::{examplesdir}/grails-app/domain/cascade/Person.groovy[tag=domain]
----

[source,groovy]
----
include::{examplesdir}/grails-app/domain/cascade/PhoneNumber.groovy[tag=domain]
----

[source,groovy]
----
include::{examplesdir}/grails-app/domain/cascade/TelephoneType.groovy[tag=domain]
----

When `Person.validate()` runs, the plugin validates every `PhoneNumber` instance in the `phoneNumbers` collection,
because `cascaded: true` is configured for that property.
When each `PhoneNumber` is validated, `cascaded` is applied again to its `TelephoneType`.

=== Service usage

In a data service you can save, and validation is applied automatically:

[source,groovy]
----
include::{examplesdir}/grails-app/services/cascade/PersonDataService.groovy[]
----

See the test case:

[source,groovy]
----
include::{examplesdir}/src/integration-test/groovy/cascade/PersonDataServiceSpec.groovy[]
----

=== Data binding usage

When binding data to `grails.validation.Validateable` objects (for example via controllers or REST endpoints), calling
`validate()` — or relying on automatic validation in data-binding flows — makes the `CascadedConstraint` validate the
marked associations as part of the root object's validation.

==== A one-to-one relationship

[source,groovy]
----
include::{plugindir}/src/test/groovy/grails/cascade/validation/support/ValidateableParent.groovy[tag=code]
----

[source,groovy]
----
include::{plugindir}/src/test/groovy/grails/cascade/validation/support/ValidateableProperty.groovy[tag=code]
----

==== A one-to-many relationship

[source,groovy]
----
include::{plugindir}/src/test/groovy/grails/cascade/validation/support/ValidateableParentWithChildList.groovy[tag=code]
----

[source,groovy]
----
include::{plugindir}/src/test/groovy/grails/cascade/validation/support/ValidateableProperty.groovy[tag=code]
----

=== Unit testing

To unit-test your cascaded associations it is important to register the cascaded constraint first.
Add the following to your `void setup() {}` block:

[source,groovy]
----
include::{examplesdir}/src/test/groovy/cascade/PersonCascadeSpec.groovy[tag=initialize]
----

See `examples/cascade-validation-example/src/test/groovy/cascade/PersonCascadeSpec.groovy` for more examples.
